set number
set incsearch
set foldlevel=3
set textwidth=80
set tabstop=2
set expandtab
set shiftwidth=2
set ignorecase
set modeline

" Enable filetype detection and loading filetype-specific plugin and
" indent files.
filetype plugin indent on
